spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://10.19.218.137:5432/prod_rtn_copy
    username: postgres
    password: u9Xb3tVE
logging:
  level:
    org.springframework.jdbc.core: TRACE

files:
  output-file-name: output/ExportToExcel.xlsx
  input-sql-query: applicationJdbc.sql