spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${URL}
    username: ${USERNAME}
    password: ${PASSWORD}
logging:
  level:
    org.springframework.jdbc.core: TRACE

files:
  output-file-name: output/ExportToExcel.xlsx
  input-sql-query: applicationJdbc.sql