spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${URL}
    username: ${USERNAME}
    password: ${PASSWORD}

files:
  output-file-name: output/ExportToExcel.xlsx
  input-sql-query-application: application.sql
  input-sql-query-atomic-application: applicationAtomic.sql
  decision-map: guides/decision-guide.yaml
  organization-code: guides/organization-code-guide.yaml
  application-guide: guides/application-guide.yaml